import static java.lang.Class.forName; 
import java.lang.System.Logger; 
import java.lang.System.Logger.Level; 
import javax.swing.JOptionPane; 
import java.sql.ResultSet; 
import java.sql.DriverManager; 
import java.sql.JDBCType; 
import java.sql.PreparedStatement; 
import java.sql.*; 
import javax.swing.*; 
import java.awt.*; 
import java.sql.Statement; 
import java.sql.Connection; 
public class login1 extends javax.swing.JFrame { 
 
    /** 
     * Creates new form login1 
     */ 
    public login1() { 
        initComponents(); 
    } 
 
    /** 
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor. 
     */ 
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private void initComponents() { 
 
        jTextField1 = new javax.swing.JTextField(); 
        jPasswordField1 = new javax.swing.JPasswordField(); 
        jLabel1 = new javax.swing.JLabel(); 
        jLabel2 = new javax.swing.JLabel(); 
        jLabel3 = new javax.swing.JLabel(); 
        jButton1 = new javax.swing.JButton(); 
        jLabel4 = new javax.swing.JLabel(); 
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
        getContentPane().setLayout(null); 
 
        jTextField1.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jTextField1ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jTextField1); 
        jTextField1.setBounds(288, 134, 112, 20); 
 
        jPasswordField1.setText("jPasswordField1"); 
        getContentPane().add(jPasswordField1); 
        jPasswordField1.setBounds(288, 165, 112, 20); 
 
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N 
        jLabel1.setForeground(new java.awt.Color(255, 0, 153)); 
        jLabel1.setText("Username:"); 
        getContentPane().add(jLabel1); 
        jLabel1.setBounds(209, 134, 61, 14); 
 
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N 
        jLabel2.setForeground(new java.awt.Color(255, 0, 102)); 
        jLabel2.setText("Password:"); 
        getContentPane().add(jLabel2); 
        jLabel2.setBounds(213, 168, 57, 14); 
 
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N 
        jLabel3.setForeground(new java.awt.Color(0, 255, 255)); 
        jLabel3.setText("SIGN IN"); 
        getContentPane().add(jLabel3); 
        jLabel3.setBounds(288, 87, 102, 29); 
 
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N 
        jButton1.setForeground(new java.awt.Color(0, 153, 255)); 
        jButton1.setText("Log In"); 
        jButton1.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton1ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton1); 
        jButton1.setBounds(288, 203, 70, 23); 
 
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\background-đẹp-3-1.jpg")); // NOI18N 
        jLabel4.setText("jLabel4"); 
        getContentPane().add(jLabel4); 
        jLabel4.setBounds(0, 0, 400, 300); 
 
        pack(); 
    }// </editor-fold> 
 
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here: 
    } 
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
        try { 
            this.login(); 
        } catch (SQLException ex) { 
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        } 
    } 
 
    /** 
     * @param args the command line arguments 
     */ 
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */ 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> 
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. 
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ 
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { 
                if ("Nimbus".equals(info.getName())) { 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
                    break; 
                } 
            } 
        } catch (ClassNotFoundException ex) { 
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (InstantiationException ex) { 
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (IllegalAccessException ex) { 
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
        } 
        //</editor-fold> 
 
        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(() -> { 
            new login1().setVisible(true); 
        }); 
    } 
 
    // Variables declaration - do not modify 
    private javax.swing.JButton jButton1; 
    private javax.swing.JLabel jLabel1; 
    private javax.swing.JLabel jLabel2; 
    private javax.swing.JLabel jLabel3; 
    private javax.swing.JLabel jLabel4; 
    private javax.swing.JPasswordField jPasswordField1; 
    private javax.swing.JTextField jTextField1; 
    // End of variables declaration 
 
    private void login() throws SQLException { s
 
        //Lay thong tin nhap vao trong hai o textbox 
        String username = jTextField1.getText(); 
        String password = String.valueOf(jPasswordField1.getPassword()); 
        try{ 
            //Viet code kiem tra ket noi co so du lieu va kiem tra dang nhap 
 
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql_db","root",""); 
 
 
            Statement st =conn.createStatement(); 
            ResultSet rs =st.executeQuery("select* from id where username ='"+username+"'and password ='"+password+"'"); 
            if(rs.next()){ 
                JOptionPane.showMessageDialog(null, "Chao mung!"); 
 
            }else{ 
                JOptionPane.showMessageDialog(rootPane, "Sai thong tin dang nhap","Warning",JOptionPane.WARNING_MESSAGE); 
            } 
        }catch(SQLException e){ 
            JOptionPane.showMessageDialog(null, "co loi xay ra!! Vui long kiem tra lai!","Warning!!",JOptionPane.ERROR_MESSAGE); 
        } 
 
    } 
 
} 